### ISSUE TITLE
mysql的数据库怎么初始化？

### ISSUE THREAD

**Issue by zhanglt** [wq1019/cloud_disk#1]
mysql的数据库怎么初始化？

**Comment by wq1019** [comment]
对不起，这个项目我还没有完成，正在开发中，你可以看一下部署脚本里面的`README.md`

**Comment by sunl888** [comment]
> mysql的数据库怎么初始化？

sorry, 这个项目我还没有完成, 你可以看一下部署脚本里面的`README.md`
这只是一个 api 服务，前端的代码不在这里

**Comment by zhanglt** [comment]
好吧，，
